apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: busybox1
spec:
  containers:
  - name: busybox1
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - crontab -l 
    livenessProbe:
      exec:
        command:
        - cat /tmp/healthy
        - scripts/ ./uname.sh 
      initialDelaySeconds: 10
      periodSeconds: 10
