apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: busybox1
spec:
  containers:
  - name: busybox1
    image: k8s.gcr.io/busybox
    livenessProbe:
      exec:
        command:
        - ./uname.sh scripts/
      initialDelaySeconds: 10
      periodSeconds: 10
