apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    spec:
      volumes:
      - name: app-data-claim
        persistentVolumeClaim:
          claimName: app-data-claim
      containers:
      - name: nginx-pod
        image: nginx:1.14.0
        - name: NGINX_ROOT_PASSWORD
          value: {$PASSWORD}
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: 
          mountPath: /usr/share/nginx/html
