apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        
      # to expose NodePort on port 81 run cmd: 
      # kubectl expose -f replicaset.yaml --type=NodePort --name=nginx-rs3 --port=81
