apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  capacity:
    storage: 1Gi
  volumes:
  - name:  
    hostPath:
    path: /data/app-data
  accessModes:
    - ReadWriteOnce
  storageClassName: standart

